### ISSUE TITLE
Client with ChatAlert not starting on Forge 10.13.4.1558

### ISSUE THREAD

**Issue by Lachney** [iLexiconn/ChatAlert#1]
Looks like it's failing to download LLibrary.
The problem is happening with ChatAlert 0.2.0
It's working with ChatAlert 0.1.2 however.
http://i.imgur.com/3cypuUa.png

However to fix my problem I had to install the old version let it download the dependency and then install the new version~

**Comment by iLexiconn** [comment]
When you install ChatAlert 0.2.0 or up, you also need LLibrary 0.6.0 or up. You can download it right [here](http://minecraft.curseforge.com/projects/llibrary/files/2269388).
